
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkvgsncuexhxdsqjxtiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrdmdzbmN1ZXhoeGRzcWp4dGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MjgxOTAsImV4cCI6MjA2MTUwNDE5MH0.cQ8B85_a_CSFJ6fLm1eTMdoXdcsbnpNkqJ4qwPTAML4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
