// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxgbsauqoozdxfyrqohi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4Z2JzYXVxb296ZHhmeXJxb2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NzMxMTMsImV4cCI6MjA2MDQ0OTExM30.QKXkAzLDLPnX5Oi6DpAxjEocE4gZICnvLzdTFZs_Dls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);